version: "3.0"

services:
  test-db:
    image: mongo:latest
    container_name: tttserver-test-db
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: ttt
