packages:
  - "packages/*"

allowBuilds:
  bcrypt: true
  core-js: true
  mongodb-memory-server: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - qs@6.15.2
  - ws@7.5.11
  - form-data@4.0.6
  - js-yaml@4.1.2
  - '@babel/core@7.29.1'
  - '@louriest/envisor@1.0.0'
overrides:
  braces@<3.0.3: '>=3.0.3'
  js-yaml@<=4.1.1: ^4.1.2
  json5@<1.0.2: '>=1.0.2'
  micromatch@<4.0.8: '>=4.0.8'
